name: docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build deps
        run: |
          pip install mudkip maturin

      - name: Build and update docs
        run: |
          maturin build
          wheel_file=$(find target/wheels -name "*.whl")
          pip install "$wheel_file" 
          mudkip build --check --update-gh-pages --repository https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/jaynewey/baskerville_py
